Metric redesign
prime-slam/evops-metrics pull request #2
Opened 2022-10-31 19:49 UTC by DmiitriyJarosh

2022-11-01 10:41 UTC, anastasiia-kornilova requested changes
1. Don't like `get_tp` name, sounds like it will return some instances whereas we have only count. `calc_tp` is more preferable.
2. Too many separation of metrics (Default/Detailed/etc), let's have only two types of modules -- point-based and plane-based. No need for more separation, will be unclear for user.
3. `__filter_unsegmented` -- doesn't have documentation
4. `np.where(gt_labels == gt_label)[0]` pattern I would move to some util function, it is used everywhere

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/metrics/DefaultBenchmark.py
> +    if unique_pred_labels_count == 0:
Looks like it could be converted in trinary operator

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/metrics/DefaultBenchmark.py
> +    if unique_gt_labels_count == 0:
Looks like it could be converted in trinary operator

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/metrics/DetailedBenchmark.py
> +def __detailed_benchmark(
Why do we call it `detailed`?

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/metrics/DetailedBenchmark.py
> +        else 0.0,
Better to move trinary intp one line, difficult to read

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/metrics/MeanBenchmark.py
> +    if len(mean_array) == 0:
trinary operator

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/metrics/constants.py
> +IOU_THRESHOLD_FULL = 0.75
Please, comment in the code what for stands every parameter

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/utils/IoUOverlap.py
> +    if threshold is None:
Why not default value to func parameters?

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/utils/MetricsUtils.py
> +    Calculate if planes are overlapped enough with IoU to be used for PP-PR metric
What is PP-PR metric?

2022-11-01 10:41 UTC, anastasiia-kornilova commented on src/evops/utils/MetricsUtils.py
> +    1) true if planes are overlapping fully by full_overlap_threshold threshold or more, false otherwise
Why not two different functions per each? Looks strange and not clear from func name.

2022-11-01 20:59 UTC, DmiitriyJarosh commented on src/evops/metrics/DefaultBenchmark.py
> +    if unique_pred_labels_count == 0:
fixed

2022-11-01 20:59 UTC, DmiitriyJarosh commented on src/evops/metrics/DefaultBenchmark.py
> +    if unique_gt_labels_count == 0:
fixed

2022-11-01 21:01 UTC, DmiitriyJarosh commented on src/evops/metrics/DetailedBenchmark.py
> +        else 0.0,
this is black, can't do anything

2022-11-01 21:02 UTC, DmiitriyJarosh commented on src/evops/metrics/DetailedBenchmark.py
> +        else 0.0,
fixed by extra variable, okey?

2022-11-01 21:03 UTC, DmiitriyJarosh commented on src/evops/metrics/MeanBenchmark.py
> +    if len(mean_array) == 0:
fixed

2022-11-01 21:04 UTC, DmiitriyJarosh commented on src/evops/utils/IoUOverlap.py
> +    if threshold is None:
fixed

2022-11-01 21:07 UTC, DmiitriyJarosh commented on src/evops/metrics/constants.py
> +IOU_THRESHOLD_FULL = 0.75
added

2022-11-01 21:08 UTC, DmiitriyJarosh commented on src/evops/utils/MetricsUtils.py
> +    Calculate if planes are overlapped enough with IoU to be used for PP-PR metric
detailed metric here)) but it will be refactored into two functions

2022-11-01 21:14 UTC, DmiitriyJarosh commented on src/evops/utils/MetricsUtils.py
> +    1) true if planes are overlapping fully by full_overlap_threshold threshold or more, false otherwise
removed this func as it is used in single place and just gathered two calls

2022-11-01 21:29 UTC, DmiitriyJarosh commented on src/evops/utils/IoUOverlap.py
> +    if threshold is None:
can't be done -- as we have to override this constant in runtime, but as default arg its value will be stored on import and can't be overriden after

2022-11-04 12:55 UTC, anastasiia-kornilova approved these changes

2022-11-04 13:26 UTC, merged